<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class SystemLog extends Model
{
    /**
     * ============================================================
     * TABLE
     * ============================================================
     */
    protected $table = 'system_logs';

    /**
     * system_logs only has created_at.
     *
     * Therefore Laravel's automatic created_at/updated_at
     * handling is disabled.
     */
    public $timestamps = false;

    /**
     * system_logs.id is a BIGINT generated by $table->id().
     *
     * These are Laravel's defaults, but they are made explicit
     * here for clarity.
     */
    protected $primaryKey = 'id';

    public $incrementing = true;

    protected $keyType = 'int';

    /**
     * ============================================================
     * MASS ASSIGNMENT
     * ============================================================
     */
    protected $fillable = [
        'user_id',
        'action',
        'module',
        'resource_type',
        'resource_id',
        'description',
        'old_values',
        'new_values',
        'request_id',
        'ip_address',
        'user_agent',
        'metadata',
        'created_at',
    ];

    /**
     * ============================================================
     * CASTS
     * ============================================================
     */
    protected $casts = [
        'old_values' => 'array',
        'new_values' => 'array',
        'metadata' => 'array',
        'created_at' => 'datetime',
    ];

    /**
     * ============================================================
     * USER / ACTOR
     * ============================================================
     *
     * The user who performed the action.
     *
     * user_id is UUID because users.id is UUID.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(
            User::class,
            'user_id',
            'id'
        );
    }

    /**
     * ============================================================
     * QUERY SCOPE: ACTION
     * ============================================================
     */
    public function scopeAction(
        Builder $query,
        string $action
    ): Builder {
        return $query->where('action', $action);
    }

    /**
     * ============================================================
     * QUERY SCOPE: MODULE
     * ============================================================
     */
    public function scopeModule(
        Builder $query,
        string $module
    ): Builder {
        return $query->where('module', $module);
    }

    /**
     * ============================================================
     * QUERY SCOPE: RESOURCE
     * ============================================================
     *
     * resource_id is stored as VARCHAR because resources can
     * have different identifier types, including UUIDs and
     * integers.
     */
    public function scopeResource(
        Builder $query,
        string $type,
        string|int $id
    ): Builder {
        return $query
            ->where('resource_type', $type)
            ->where('resource_id', (string) $id);
    }

    /**
     * ============================================================
     * QUERY SCOPE: ACTOR
     * ============================================================
     *
     * users.id is UUID, therefore the identifier is represented
     * as string.
     */
    public function scopeByUser(
        Builder $query,
        string $userId
    ): Builder {
        return $query->where('user_id', $userId);
    }
}