<?php

enum PaymentNotificationType: string
{
    case PAYMENT_RECEIVED = 'PAYMENT_RECEIVED';
    case PAYMENT_PARTIAL = 'PAYMENT_PARTIAL';
    case PAYMENT_COMPLETED = 'PAYMENT_COMPLETED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';
    case BANK_TRANSFER_SUBMITTED = 'BANK_TRANSFER_SUBMITTED';
    case BANK_TRANSFER_VERIFIED = 'BANK_TRANSFER_VERIFIED';
    case BANK_TRANSFER_REJECTED = 'BANK_TRANSFER_REJECTED';
}