<?php

namespace App\Modules\Assessment\Services;

use App\Models\Assessment;
use App\Modules\Assessment\Requests\StoreAssessmentRequest;
use App\Services\AssessmentCalculationService;
use App\Services\DocumentSequenceService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AssessmentCreationService
{
    public function __construct(
        protected AssessmentServiceValueService $serviceValueService,
        protected AssessmentCalculationService $calculationService,
        protected DocumentSequenceService $documentSequenceService,
    ) {
    }

    /**
     * ============================================================
     * CREATE
     * ============================================================
     *
     * Responsibilities:
     *
     * - Create assessment header
     * - Generate assessment number using centralized sequence
     * - Store assessment services
     * - Store dynamic service values
     * - Calculate financial values when submitted
     * - Commit only when the complete operation succeeds
     */
    public function create(
        StoreAssessmentRequest $request
    ): Assessment {
        $assessment = DB::transaction(
            function () use ($request): Assessment {

                /*
                |--------------------------------------------------------------------------
                | Generate Assessment Number
                |--------------------------------------------------------------------------
                |
                | The document number is generated by the centralized
                | DocumentSequenceService.
                |
                | Example:
                |
                | ASM-2019-000001
                |
                | The sequence is maintained independently for:
                |
                | sequence_type + year
                |
                | This also prevents duplicate numbers under concurrent requests.
                |
                */

                $assessmentNumber =
                    $this->generateAssessmentNumber();

                /*
                |--------------------------------------------------------------------------
                | Create Assessment
                |--------------------------------------------------------------------------
                */

                $assessment = Assessment::create([
                    'id' => (string) Str::uuid(),

                    'assessment_number' =>
                        $assessmentNumber,

                    'citizen_id' =>
                        $request->taxpayerId(),

                    'assessment_date' =>
                        now()->toDateString(),

                    'status' =>
                        $request->status(),

                    'notes' =>
                        $request->validated('notes'),

                    'submitted_at' =>
                        $request->status() === 'PENDING_APPROVAL'
                            ? now()
                            : null,

                    'created_by' =>
                        auth()->id(),
                ]);

                /*
                |--------------------------------------------------------------------------
                | Store Services
                |--------------------------------------------------------------------------
                */

                $this->serviceValueService->storeServices(
                    $assessment,
                    $request->services()
                );

                /*
                |--------------------------------------------------------------------------
                | CALCULATE BEFORE COMMIT
                |--------------------------------------------------------------------------
                |
                | If calculation fails, Laravel automatically rolls back
                | the entire transaction:
                |
                | - assessment
                | - assessment services
                | - assessment values
                | - calculation changes
                |
                */

                if (
                    $assessment->status ===
                    'PENDING_APPROVAL'
                ) {
                    $this->calculationService->calculate(
                        $assessment
                    );
                }

                return $assessment;
            }
        );

        /*
        |--------------------------------------------------------------------------
        | Return Fresh Assessment
        |--------------------------------------------------------------------------
        */

        return $assessment->fresh([
            'taxpayer',
            'creator',
            'updater',
            'decisionOfficer',
            'services',
            'services.service',
            'services.values',
            'services.values.files',
        ]);
    }

    /**
     * ============================================================
     * ASSESSMENT NUMBER
     * ============================================================
     *
     * Generate the next assessment document number.
     *
     * Uses the centralized DocumentSequenceService.
     *
     * Example:
     *
     * ASM-2019-000001
     * ASM-2019-000002
     * ASM-2019-000003
     *
     * The calendar is explicitly set to Ethiopian because
     * municipal document numbering uses the Ethiopian calendar.
     */
    protected function generateAssessmentNumber(): string
    {
        return $this->documentSequenceService->generate(
            sequenceType: 'assessment',
            prefix: 'ASM',
            calendar: 'ethiopian',
        );
    }
}
